const mockArticles = [
  {
    id: 1,
    slug: "ia-y-el-futuro-del-desarrollo",
    title: "IA y el futuro del desarrollo de software",
    excerpt:
      "Los modelos de lenguaje están redefiniendo cómo escribimos código. Analizamos cómo herramientas como Copilot y Claude están cambiando el día a día del desarrollador y qué habilidades cobran más relevancia.",
    image: "https://picsum.photos/seed/article1/600/320",
    date: "20 de Febrero, 2026",
    author: "Egoi",
    readTime: "6 min",
    tag: "IA",
    body: [
      "Durante años, la figura del desarrollador de software estuvo asociada a una combinación de conocimiento técnico profundo, capacidad de abstracción y mucha tolerancia a la frustración. Hoy, esa imagen está mutando. Las herramientas basadas en inteligencia artificial no solo autocompletan código: proponen arquitecturas, detectan bugs en tiempo real y generan tests a partir de comentarios en lenguaje natural.",
      "Copilot, Claude, Cursor y decenas de herramientas similares han pasado de ser curiosidades de laboratorio a integrarse en los flujos de trabajo reales de empresas de todos los tamaños. El impacto es doble: por un lado, la velocidad de desarrollo se multiplica. Por otro, el umbral de entrada se reduce drásticamente. Un desarrollador junior con buen criterio y las herramientas adecuadas puede producir código que antes requería años de experiencia.",
      "Esto no significa que los desarrolladores vayan a desaparecer. Significa que cambia lo que se les pide. La capacidad de evaluar críticamente el código generado, de entender las implicaciones de arquitectura, de comunicar con precisión los requerimientos a los modelos… estas habilidades se vuelven centrales. El desarrollador evoluciona hacia un rol más cercano al director de orquesta que al músico solista.",
      "El riesgo real no es que la IA sustituya a los programadores, sino que los programadores que no la adopten pierdan relevancia frente a los que sí lo hacen. La brecha no será entre humanos y máquinas, sino entre quienes sepan colaborar con estas herramientas y quienes las ignoren.",
      "En los próximos años veremos una redefinición del mercado laboral técnico. Las empresas ya no buscan solo saber qué lenguajes dominas, sino cómo trabajas con asistentes de IA, cómo iteras, cómo validas y cómo mantienes la autoría intelectual sobre el código que produces. El futuro no es menos código: es más código, mejor código, con menos fricción.",
    ],
  },
  {
    id: 2,
    slug: "estrategia-seo-2026",
    title: "Estrategia SEO en 2026: lo que realmente funciona",
    excerpt:
      "El SEO ha evolucionado más en los últimos dos años que en la década anterior. Repasamos las tácticas que siguen siendo efectivas y cuáles han quedado obsoletas con la búsqueda generativa.",
    image: "https://picsum.photos/seed/article2/600/320",
    date: "14 de Febrero, 2026",
    author: "Egoi",
    readTime: "8 min",
    tag: "Marketing",
    body: [
      "La búsqueda generativa lo ha cambiado todo. Desde que Google integró las respuestas de IA en la parte superior de los resultados, el tráfico orgánico hacia muchos sitios web cayó entre un 20% y un 40% en verticales informacionales. Las páginas de 'qué es X' o 'cómo hacer Y' ya no funcionan como antes porque el usuario recibe la respuesta directamente en el buscador.",
      "Dicho esto, el SEO no ha muerto. Ha evolucionado. Las páginas que siguen captando tráfico de calidad son aquellas que aportan algo que la IA no puede replicar fácilmente: opinión experta contrastada, datos propios, estudios de caso, experiencia de primera mano. El contenido EEAT (Experience, Expertise, Authoritativeness, Trustworthiness) nunca ha sido tan relevante.",
      "En términos técnicos, lo que no ha cambiado: la velocidad de carga sigue importando, los Core Web Vitals siguen siendo un factor de ranking, y la indexabilidad correcta es la base sobre la que se construye todo lo demás. Lo que ha cambiado: el enfoque en palabras clave exactas ha cedido terreno al entendimiento semántico. Google ya no busca que repitas la keyword diez veces; busca que el documento sea la respuesta más completa y fiable sobre el tema.",
      "Para 2026, las estrategias que están funcionando son las de contenido pilar con clusters temáticos, el link building basado en relaciones reales y menciones en medios de autoridad, y el SEO técnico aplicado a datos estructurados que alimentan los fragmentos de IA. Quien entienda cómo los modelos de lenguaje consumen e interpretan el contenido web tendrá una ventaja real.",
      "La recomendación práctica es dejar de pensar en páginas y empezar a pensar en entidades y relaciones. Tu sitio debe ser reconocido por los sistemas de IA como una fuente de referencia en un ámbito concreto. Eso requiere consistencia, profundidad temática y una presencia externa que valide tu autoridad. No es un sprint, es un maratón. Pero sigue siendo una de las inversiones más rentables en marketing digital.",
    ],
  },
  {
    id: 3,
    slug: "react-server-components-en-produccion",
    title: "React Server Components en producción: lecciones aprendidas",
    excerpt:
      "Llevamos seis meses con RSC en producción. Esto es lo que aprendimos sobre rendimiento, hidratación y los patrones que realmente escalan en aplicaciones grandes.",
    image: "https://picsum.photos/seed/article3/600/320",
    date: "8 de Febrero, 2026",
    author: "Egoi",
    readTime: "10 min",
    tag: "Desarrollo",
    body: [
      "Cuando anunciaron React Server Components, la comunidad se dividió en dos campos: los que veían una revolución en la arquitectura frontend y los que pensaban que era un paso atrás hacia el renderizado servidor de los años 2000. Seis meses después de llevarlo a producción en una aplicación con más de 50.000 usuarios diarios, tenemos datos reales para opinar.",
      "La mejora de rendimiento inicial es genuina. Reducir el JavaScript que se envía al cliente eliminando la hidratación de componentes que no necesitan interactividad es un win claro. En nuestro caso, el bundle de la página principal bajó un 35% y el LCP mejoró en torno a 800ms en conexiones lentas. No es magia, pero es significativo.",
      "El mayor reto no es técnico, sino mental: cambiar el modelo de razonamiento del equipo. La pregunta ya no es '¿funciona este componente?' sino '¿dónde debe ejecutarse este componente?'. Los errores más frecuentes que vimos fueron: intentar usar hooks en Server Components, no entender bien la frontera entre server y client, y confundir el caché de Next.js con el estado de React.",
      "El patrón que mejor nos funcionó fue el de 'server shell, client islands'. Los componentes de layout, navigation y contenido estático son Server Components. Los formularios, modales, interacciones complejas y cualquier cosa que dependa del estado del usuario son Client Components. La clave es minimizar el número de componentes marcados con 'use client' y agruparlos en hojas del árbol, no en la raíz.",
      "¿Vale la pena migrar? Depende del proyecto. Para aplicaciones nuevas con Next.js 14+, el App Router con RSC debería ser el punto de partida. Para aplicaciones existentes grandes, la migración incremental es posible pero requiere planificación. Para proyectos pequeños o con muchas interacciones dinámicas, el beneficio puede no justificar el coste de aprendizaje del equipo.",
    ],
  },
  {
    id: 4,
    slug: "diseno-de-interfaces-para-ia",
    title: "Diseñando interfaces para productos con IA",
    excerpt:
      "Cuando la respuesta puede tardar segundos o ser inesperada, el diseño de UX cambia radicalmente. Patrones de loading, feedback y expectativas del usuario en aplicaciones de IA.",
    image: "https://picsum.photos/seed/article4/600/320",
    date: "1 de Febrero, 2026",
    author: "Egoi",
    readTime: "7 min",
    tag: "Diseño",
    body: [
      "Diseñar para inteligencia artificial tiene una particularidad que lo separa del diseño de software tradicional: la respuesta del sistema no es determinista. No puedes predecir exactamente qué va a responder el modelo, cuánto va a tardar ni en qué formato va a llegar la información. Esto obliga a repensar patrones de UX que dábamos por sentados.",
      "El loading state es el primer desafío. En una app convencional, el spinner dura menos de un segundo. En una aplicación con LLMs, la respuesta puede tardar entre 2 y 15 segundos dependiendo de la complejidad. Un spinner estándar genera ansiedad pasado cierto umbral. Las soluciones que mejor funcionan son el streaming progresivo del texto (el usuario ve cómo se va construyendo la respuesta) y los mensajes de estado contextuales que explican qué está haciendo el sistema.",
      "El feedback de errores es otro punto crítico. Los modelos de lenguaje pueden dar respuestas incorrectas con total confianza. El diseño debe contemplar mecanismos de corrección accesibles: botones de regeneración, edición del prompt, valoración de la respuesta. No se trata solo de usabilidad, sino de construir la confianza del usuario de forma honesta.",
      "Las expectativas son quizás el elemento más subestimado. Cuando un usuario interactúa por primera vez con un producto de IA, trae consigo una imagen formada por películas de ciencia ficción y por herramientas como ChatGPT. El diseño debe calibrar esas expectativas desde el onboarding: mostrar casos de uso reales, ejemplos de lo que funciona bien y ser transparente sobre las limitaciones.",
      "El diseño de interfaces para IA es una disciplina emergente y todavía estamos aprendiendo. Los patrones que funcionan hoy pueden quedar obsoletos en seis meses a medida que mejoran los modelos. Lo que no cambia es la necesidad de diseñar desde la empatía con el usuario y con honestidad sobre lo que el sistema puede y no puede hacer.",
    ],
  },
  {
    id: 5,
    slug: "automatizacion-de-marketing-con-ia",
    title: "Automatización de marketing con IA: guía práctica",
    excerpt:
      "Desde segmentación hasta generación de contenido, la IA está automatizando tareas que antes requerían equipos enteros. Herramientas, flujos de trabajo y casos de uso reales.",
    image: "https://picsum.photos/seed/article5/600/320",
    date: "25 de Enero, 2026",
    author: "Egoi",
    readTime: "9 min",
    tag: "Marketing",
    body: [
      "El marketing lleva años hablando de personalización a escala como si fuera el santo grial. La promesa siempre fue la misma: tratar a cada cliente como si fuera el único, pero hacerlo con millones de personas simultáneamente. Hasta hace poco, eso era una aspiración más que una realidad. Con la IA generativa, la ecuación cambia.",
      "En el área de contenido, las ganancias de productividad son inmediatas. Un equipo que antes tardaba una semana en producir diez artículos ahora puede generar cien borradores en un día, editarlos en dos y publicarlos en tres. Pero el contenido generado por IA sin supervisión editorial se nota, y Google lo penaliza. El modelo que funciona es el humano como editor estratégico y la IA como motor de producción.",
      "La segmentación y personalización es donde la IA aporta valor de forma menos visible pero más profunda. Los modelos predictivos identifican patrones de comportamiento que ningún analista humano encontraría en un dataset grande. Herramientas como Customer.io o Klaviyo ya integran IA para predecir el momento óptimo de envío, el contenido más relevante por segmento y la probabilidad de churn antes de que ocurra.",
      "Los flujos de automatización más efectivos que hemos visto combinan triggers basados en comportamiento real (no solo en fechas o segmentos estáticos) con mensajes generados o seleccionados por IA según el perfil del usuario. El resultado son tasas de apertura un 30-40% superiores a las de campañas genéricas.",
      "El error más común es intentar automatizar demasiado de golpe. La recomendación práctica es empezar por un flujo de alto impacto (bienvenida, recuperación de carrito, win-back) y medir con rigor antes de escalar. La IA no reemplaza una estrategia de marketing; la potencia. Sin estrategia clara, más automatización solo acelera el ruido.",
    ],
  },
  {
    id: 6,
    slug: "rendimiento-web-core-web-vitals",
    title: "Core Web Vitals en 2026: guía definitiva de rendimiento",
    excerpt:
      "Google sigue usando los CWV como factor de ranking. Cubrimos INP, LCP y CLS con técnicas actualizadas, herramientas de medición y los errores más comunes en Next.js.",
    image: "https://picsum.photos/seed/article6/600/320",
    date: "18 de Enero, 2026",
    author: "Egoi",
    readTime: "12 min",
    tag: "Tecnología",
    body: [
      "Los Core Web Vitals llevan desde 2021 siendo factor de ranking en Google, pero su importancia real sigue siendo subestimada. No porque no importen, sino porque la mayoría de los equipos de desarrollo los trata como un checklist de último momento en lugar de como una disciplina continua. En 2026, con INP reemplazando definitivamente a FID, la cosa se complica un poco más.",
      "El Largest Contentful Paint (LCP) sigue siendo el más comprensible de los tres: mide cuánto tarda en cargarse el elemento visible más grande de la página. El objetivo es menos de 2.5 segundos. Los culpables habituales son imágenes sin optimizar, fuentes web bloqueantes y servidores lentos. En Next.js, el componente Image resuelve buena parte del problema automáticamente, pero solo si lo usas correctamente con los atributos priority en elementos above the fold.",
      "El Cumulative Layout Shift (CLS) es el que más frustra a los usuarios aunque no sepan nombrarlo. Ese salto de contenido cuando se carga un anuncio o una imagen sin dimensiones declaradas es CLS puro. La solución técnica es sencilla: declarar siempre width y height en imágenes, reservar espacio para contenido dinámico con aspect-ratio, y evitar insertar contenido sobre el existente después de la carga inicial.",
      "El Interaction to Next Paint (INP) es el nuevo y el más difícil de optimizar. Mide la latencia de todas las interacciones del usuario durante la visita, no solo la primera. Un componente React que hace demasiado en el hilo principal, un event listener que bloquea, una operación síncrona costosa… todo impacta en INP. Las herramientas clave son el Profiler de Chrome DevTools y PerformanceObserver en producción.",
      "En proyectos Next.js, los errores más frecuentes que vemos son: usar useEffect para cargar datos que podrían venir del servidor, no aprovechar el caché de Next.js, importar librerías pesadas en componentes cliente sin dynamic import, y no configurar correctamente las políticas de caché de imágenes. La buena noticia es que la mayoría son solucionables con cambios relativamente pequeños.",
    ],
  },
  {
    id: 7,
    slug: "prompting-para-desarrolladores",
    title: "Prompting avanzado para desarrolladores",
    excerpt:
      "El prompt engineering no es solo para científicos de datos. Técnicas de chain-of-thought, few-shot learning y estructuración de contexto que todo desarrollador debería conocer.",
    image: "https://picsum.photos/seed/article7/600/320",
    date: "10 de Enero, 2026",
    author: "Egoi",
    readTime: "8 min",
    tag: "IA",
    body: [
      "Cuando los modelos de lenguaje empezaron a popularizarse, la idea de que 'hablar bien con la IA' era una habilidad profesional sonaba casi a broma. Dos años después, el prompt engineering está en los perfiles de LinkedIn de ingenieros senior de las principales tecnológicas del mundo. No es una moda: es una competencia real con impacto directo en la calidad del output.",
      "La técnica más documentada y efectiva es el chain-of-thought prompting. En lugar de pedir directamente la respuesta final, guías al modelo para que razone paso a paso. La diferencia de calidad en tareas complejas es notable: el modelo comete menos errores lógicos, encuentra más casos edge y produce código más robusto. La variante más sencilla es añadir 'Piensa paso a paso antes de responder' o estructurar el prompt con fases explícitas.",
      "El few-shot learning es igualmente poderoso cuando el output necesita seguir un formato muy concreto. Mostrar dos o tres ejemplos del resultado esperado antes de hacer la pregunta calibra el modelo de forma que mil palabras de instrucciones no logran. Para tareas de generación de código, tests o transformaciones de datos, los ejemplos son la herramienta más eficiente.",
      "La gestión del contexto es donde la mayoría de los desarrolladores pierden rendimiento. Los modelos tienen una ventana de contexto limitada y no toda la información tiene el mismo peso. Poner las instrucciones críticas al principio y al final del prompt (no solo al principio), ser explícito sobre el rol que debe asumir el modelo, y eliminar información redundante son prácticas que mejoran consistentemente los resultados.",
      "Un error frecuente es tratar el prompt como algo inmutable. El prompting efectivo es iterativo. Prueba, mide, ajusta. Guarda los prompts que funcionan como plantillas reutilizables. En equipos de desarrollo, compartir una librería de prompts efectivos para tareas recurrentes (code review, generación de tests, documentación) puede multiplicar la productividad de todo el equipo.",
    ],
  },
  {
    id: 8,
    slug: "sistemas-de-diseno-escalables",
    title: "Cómo construir un sistema de diseño que escale",
    excerpt:
      "Tokens, componentes atómicos, documentación viva. Repasamos los pilares de un design system que sobrevive al crecimiento del equipo y a los cambios de marca.",
    image: "https://picsum.photos/seed/article8/600/320",
    date: "3 de Enero, 2026",
    author: "Egoi",
    readTime: "11 min",
    tag: "Diseño",
    body: [
      "La mayoría de los sistemas de diseño mueren por el mismo motivo: empezaron bien pero nadie los mantuvo. El componente Button tiene cinco variantes no documentadas, el color primario está hardcodeado en veinte sitios distintos, y el equipo de diseño trabaja con una versión de Figma que ya no se corresponde con lo que hay en producción. Construir un design system es relativamente fácil; mantenerlo vivo es el verdadero reto.",
      "El punto de partida correcto no son los componentes, son los tokens. Los tokens de diseño son las unidades atómicas del sistema: colores, tipografías, espaciados, radios de borde, sombras. Cuando un cambio de marca requiere actualizar el color primario, si tienes tokens bien definidos es un cambio en un archivo. Si no los tienes, son horas de búsqueda y reemplazo en el código.",
      "Los componentes atómicos (Atomic Design de Brad Frost) siguen siendo el marco de referencia más útil para estructurar la librería. La clave no es seguirlo dogmáticamente sino entender la filosofía: construir de lo simple a lo complejo, con cada nivel dependiendo de los anteriores, y evitando la duplicación. Un Button bien construido no debería necesitar reescribirse para cada contexto en el que aparece.",
      "La documentación es donde los sistemas de diseño suelen fallar. Storybook ha mejorado mucho en los últimos años y sigue siendo el estándar, pero su valor es directamente proporcional a la disciplina del equipo para mantenerlo actualizado. La documentación que nadie lee no sirve de nada. La solución es integrar la documentación en el flujo de trabajo: no como una tarea separada, sino como parte del definition of done de cada componente.",
      "Para que un design system sobreviva al crecimiento del equipo necesita un propietario claro (una persona o un equipo pequeño dedicado), un proceso de contribución documentado y un ciclo de versiones predecible. Los sistemas más exitosos que hemos visto tratan sus componentes como un producto interno: con roadmap, con breaking changes anunciados y con soporte a los equipos que los consumen.",
    ],
  },
  {
    id: 9,
    slug: "apis-rest-vs-graphql-en-2026",
    title: "REST vs GraphQL en 2026: ¿cuándo usar cada uno?",
    excerpt:
      "Con el auge de tRPC y las APIs generadas automáticamente por IA, el debate REST/GraphQL ha ganado nuevas aristas. Un análisis honesto de trade-offs según el tipo de proyecto.",
    image: "https://picsum.photos/seed/article9/600/320",
    date: "27 de Diciembre, 2025",
    author: "Egoi",
    readTime: "7 min",
    tag: "Desarrollo",
    body: [
      "El debate REST vs GraphQL lleva años siendo una de esas discusiones técnicas que generan más calor que luz. En 2026, con tRPC ganando adopción masiva en el ecosistema TypeScript y con herramientas de IA capaces de generar clientes API automáticamente a partir de especificaciones, el panorama es más matizado que nunca. La respuesta correcta sigue siendo 'depende', pero ahora podemos ser más precisos sobre de qué depende.",
      "REST sigue siendo la opción por defecto para APIs públicas, integraciones con terceros y equipos que priorizan la simplicidad operacional. El contrato es predecible, la caché HTTP funciona sin configuración adicional, y cualquier desarrollador del mundo sabe cómo consumirla. Cuando el cliente es externo o desconocido, REST es la opción más robusta.",
      "GraphQL brilla en aplicaciones con múltiples clientes que necesitan datos diferentes del mismo backend. Un dashboard de administración, una app móvil y una web pública raramente necesitan exactamente los mismos campos. Con GraphQL, cada cliente pide exactamente lo que necesita, se elimina el overfetching y el underfetching, y el esquema actúa como documentación viva. El coste es la complejidad operacional: caching, seguridad, optimización de queries.",
      "tRPC es la opción que está robando cuota de mercado a ambos en proyectos full-stack donde cliente y servidor son TypeScript. La seguridad de tipos end-to-end sin generación de código y sin esquemas adicionales es una experiencia de desarrollo difícil de superar. La limitación obvia es que está acoplado al ecosistema TypeScript/JavaScript, lo que lo descarta para APIs que deben servir a múltiples tecnologías.",
      "La IA está añadiendo una dimensión nueva al debate: herramientas como Cursor o las APIs de Anthropic pueden generar clientes completos a partir de una especificación OpenAPI en minutos. Esto democratiza REST y reduce el argumento de GraphQL sobre la productividad del frontend. En 2026, la elección se hace más en función del equipo, el contexto y los requisitos de escalabilidad que de las características técnicas puras de cada protocolo.",
    ],
  },
];

export default mockArticles;
